name = "CORE API Flask Application Settings"

[default]
DEBUG = false

[development]
DATABASE_DIR = 'db/'
SQLALCHEMY_DATABASE_URI = 'sqlite:///db/main.db'

[production]
DATABASE_DIR = 'db/'
SQLALCHEMY_DATABASE_URI = 'sqlite:///db/main.db'
